import {
  DailyWorkLogEntry,
  DeveloperRosterMember,
  RepositoryMapping,
  SOPGuideData,
  UserProfile,
  MarketingDeal,
  MarketingInteraction,
  FounderMatrixStats,
  ClientMasterRecord,
  ProjectProgressRecord,
  PaymentBillingRecord,
  CompanyTopLineMetrics,
} from "./types";

// =========================================================================
// USER PROFILES (Founders, Developers, Marketing Reps)
// =========================================================================
export const INITIAL_USER_PROFILES: UserProfile[] = [
  // 4 Co-Founders & Owners
  {
    id: "user-akshar",
    name: "Akshar",
    roleTitle: "Co-Founder & Tech Lead",
    category: "founder",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
    email: "akshar@axoraa.com",
    department: "Executive Leadership & Tech",
    activeProject: "SeekFactory",
  },
  {
    id: "user-abhinav",
    name: "Abhinav",
    roleTitle: "Co-Founder & Frontend Lead",
    category: "founder",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
    email: "abhinav@axoraa.com",
    department: "Executive Leadership & Web",
    activeProject: "SeekFactory",
  },
  {
    id: "user-adnaan",
    name: "Adnaan",
    roleTitle: "Co-Founder & Platform Lead",
    category: "founder",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
    email: "adnaan@axoraa.com",
    department: "Executive Leadership & Platform",
    activeProject: "SeekFactory",
  },
  {
    id: "user-bhuvan",
    name: "Bhuvan",
    roleTitle: "Co-Founder & Mobile Lead",
    category: "founder",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
    email: "bhuvan@axoraa.com",
    department: "Executive Leadership & Mobile",
    activeProject: "SeekFactory",
  },
  // Field Marketing Specialists
  {
    id: "user-kamil",
    name: "Kamil",
    roleTitle: "Senior Field Marketing & BD Rep",
    category: "marketing",
    avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?w=120&auto=format&fit=crop&q=80",
    email: "kamil@axoraa.com",
    department: "Field Marketing & Sales",
    activeProject: "Marketing Operations",
  },
  {
    id: "user-anusha",
    name: "Anusha",
    roleTitle: "Enterprise Account Executive",
    category: "marketing",
    avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=120&auto=format&fit=crop&q=80",
    email: "anusha@axoraa.com",
    department: "Field Marketing & Sales",
    activeProject: "Marketing Operations",
  },
  // Engineering Specialists
  {
    id: "user-manish",
    name: "Manish",
    roleTitle: "Backend & DevOps Engineer",
    category: "developer",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
    email: "manish@axoraa.com",
    department: "Infrastructure",
    activeProject: "SeekFactory",
  },
  {
    id: "user-vinod",
    name: "Vinod",
    roleTitle: "QA & Automation Engineer",
    category: "developer",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80",
    email: "vinod@axoraa.com",
    department: "Quality Assurance",
    activeProject: "SeekFactory",
  },
  {
    id: "user-chakravarthi",
    name: "Chakravarthi",
    roleTitle: "Software Engineering Intern",
    category: "developer",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80",
    email: "chakravarthi@axoraa.com",
    department: "Core Engineering",
    activeProject: "SeekFactory",
  },
];

// =========================================================================
// TRACK 1: ENGINEERING & DEVELOPER TEAM DATA
// =========================================================================
export const INITIAL_ROSTER: DeveloperRosterMember[] = [
  {
    id: "dev-1",
    developerName: "Akshar",
    role: "Tech Lead / Senior Backend Engineer",
    primaryArea: "Backend Architecture & Core APIs",
    active: "Yes",
    joiningDate: "2024-01-15",
    notes: "Lead developer for SeekFactory-B & System Architecture",
    avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "dev-2",
    developerName: "Abhinav",
    role: "Senior Frontend Engineer",
    primaryArea: "Frontend Architecture & Web UI",
    active: "Yes",
    joiningDate: "2024-03-01",
    notes: "Web platform lead for SeekFactory-Web-F",
    avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "dev-3",
    developerName: "Adnaan",
    role: "Full Stack Engineer",
    primaryArea: "API Integration & Web Components",
    active: "Yes",
    joiningDate: "2024-06-10",
    notes: "Cross-stack feature development and webhook integrations",
    avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "dev-4",
    developerName: "Bhuvan",
    role: "Mobile Application Engineer",
    primaryArea: "Cross-Platform Mobile Apps",
    active: "Yes",
    joiningDate: "2024-08-01",
    notes: "Mobile client lead for SeekFactory-App-F (iOS & Android)",
    avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "dev-5",
    developerName: "Manish",
    role: "Backend & DevOps Engineer",
    primaryArea: "Database, CI/CD & Cloud Infrastructure",
    active: "Yes",
    joiningDate: "2024-09-15",
    notes: "Infrastructure, Redis clusters, and Docker pipelines",
    avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "dev-6",
    developerName: "Vinod",
    role: "QA & Full Stack Engineer",
    primaryArea: "Testing, Quality Assurance & API Validations",
    active: "Yes",
    joiningDate: "2025-01-10",
    notes: "Quality automation, Jest/Playwright, and release gating",
    avatar: "https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?w=120&auto=format&fit=crop&q=80",
  },
  {
    id: "dev-7",
    developerName: "Chakravarthi",
    role: "Software Engineering Intern",
    primaryArea: "Feature Enhancements & Bug Fixes",
    active: "Yes",
    joiningDate: "2026-06-01",
    notes: "Mentored across web dashboard and core microservices",
    avatar: "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=120&auto=format&fit=crop&q=80",
  },
];

export const INITIAL_REPOSITORIES: RepositoryMapping[] = [
  {
    id: "repo-1",
    projectName: "SeekFactory",
    repository: "SeekFactory-Web-F",
    type: "Frontend Web Application",
    status: "Active",
    description: "Next.js/React web dashboard and client portal",
  },
  {
    id: "repo-2",
    projectName: "SeekFactory",
    repository: "SeekFactory-B",
    type: "Backend Service & APIs",
    status: "Active",
    description: "Core microservices, databases, auth, and backend APIs",
  },
  {
    id: "repo-3",
    projectName: "SeekFactory",
    repository: "SeekFactory-App-F",
    type: "Mobile Client Application",
    status: "Active",
    description: "Cross-platform iOS and Android mobile applications",
  },
];

export const INITIAL_WORK_LOGS: DailyWorkLogEntry[] = [
  {
    id: "log-1",
    date: "2026-09-23",
    developerName: "Akshar",
    project: "SeekFactory",
    repository: "seekfactory-b",
    module: "Auth Microservice",
    workType: "Authentication / Authorization",
    taskDescription: "Implemented JWT refresh token rotation with Redis revocation list & distributed session lock",
    githubPr: "#142",
    workStatus: "Completed",
    priority: "Critical",
    hours: 7.5,
    isBlocked: "No",
    blockerDetails: "",
    reviewRequired: "Yes",
    reviewer: "Manish",
    deployment: "Staging",
    productionImpact: "High",
    notes: "Requires Redis cache migration before production deployment.",
    lastUpdated: "2026-09-23 15:40:12",
  },
  {
    id: "log-2",
    date: "2026-09-23",
    developerName: "Abhinav",
    project: "SeekFactory",
    repository: "seekfactory-web-f",
    module: "Project Dashboard",
    workType: "UI/UX Improvement",
    taskDescription: "Engineered ultra-responsive telemetry cards and radial compliance speedometer gauge with zero CLS",
    githubPr: "#204",
    workStatus: "Completed",
    priority: "High",
    hours: 7.0,
    isBlocked: "No",
    blockerDetails: "",
    reviewRequired: "Yes",
    reviewer: "Akshar",
    deployment: "Development",
    productionImpact: "Medium",
    notes: "Matches design system specs with neon lime (#D4FF32) accent.",
    lastUpdated: "2026-09-23 16:10:45",
  },
  {
    id: "log-3",
    date: "2026-09-23",
    developerName: "Bhuvan",
    project: "SeekFactory",
    repository: "seekfactory-app-f",
    module: "Push Notifications",
    workType: "Bug Fix / UI Enhancement",
    taskDescription: "FCM background notification handler crashing on Android 15 edge runtime",
    githubPr: "#89",
    workStatus: "Blocked",
    priority: "Critical",
    hours: 6.0,
    isBlocked: "Yes",
    blockerDetails: "Waiting for upgraded Google Services JSON & enterprise Apple Developer APNS certificate",
    reviewRequired: "Yes",
    reviewer: "Akshar",
    deployment: "Not Applicable",
    productionImpact: "High",
    notes: "Escalated to DevOps/Lead as P1 critical impediment.",
    lastUpdated: "2026-09-23 14:22:00",
  },
  {
    id: "log-4",
    date: "2026-09-23",
    developerName: "Adnaan",
    project: "SeekFactory",
    repository: "seekfactory-web-f",
    module: "Client Billing Portal",
    workType: "API Integration",
    taskDescription: "Integrated Stripe Checkout session webhook & automated tax invoice generation",
    githubPr: "#208",
    workStatus: "In Progress",
    priority: "High",
    hours: 6.5,
    isBlocked: "No",
    blockerDetails: "",
    reviewRequired: "Yes",
    reviewer: "Vinod",
    deployment: "Development",
    productionImpact: "Medium",
    notes: "Sandbox credentials tested; awaiting webhook test event payload signoff.",
    lastUpdated: "2026-09-23 15:05:10",
  },
  {
    id: "log-5",
    date: "2026-09-23",
    developerName: "Manish",
    project: "SeekFactory",
    repository: "seekfactory-b",
    module: "PostgreSQL Replica",
    workType: "DevOps / Infrastructure",
    taskDescription: "Configured read-replica pooling using PgBouncer with auto failover health probe",
    githubPr: "#145",
    workStatus: "Completed",
    priority: "High",
    hours: 8.0,
    isBlocked: "No",
    blockerDetails: "",
    reviewRequired: "Yes",
    reviewer: "Akshar",
    deployment: "Production",
    productionImpact: "High",
    notes: "Reduced peak API latency by 38% under 2500 concurrent req/sec benchmark.",
    lastUpdated: "2026-09-23 16:20:00",
  },
  {
    id: "log-6",
    date: "2026-09-23",
    developerName: "Vinod",
    project: "SeekFactory",
    repository: "seekfactory-b",
    module: "E2E Test Suite",
    workType: "Refactoring",
    taskDescription: "Automated regression tests covering client onboarding and multi-tenant permission isolation",
    githubPr: "#147",
    workStatus: "In Progress",
    priority: "Medium",
    hours: 6.0,
    isBlocked: "No",
    blockerDetails: "",
    reviewRequired: "No",
    reviewer: "-",
    deployment: "Development",
    productionImpact: "None",
    notes: "Playwright scripts passing 94% coverage on authentication flows.",
    lastUpdated: "2026-09-23 13:50:30",
  },
  {
    id: "log-7",
    date: "2026-09-23",
    developerName: "Chakravarthi",
    project: "SeekFactory",
    repository: "seekfactory-web-f",
    module: "Settings & Profile",
    workType: "Bug Fix / UI Enhancement",
    taskDescription: "Fixed avatar file upload size validation and avatar crop preview on Safari",
    githubPr: "#210",
    workStatus: "Blocked",
    priority: "Medium",
    hours: 5.5,
    isBlocked: "Yes",
    blockerDetails: "Awaiting S3 signed upload URL policy update from DevOps (Manish)",
    reviewRequired: "Yes",
    reviewer: "Abhinav",
    deployment: "Development",
    productionImpact: "Low",
    notes: "Blocked on AWS IAM policy permission for direct S3 PUT.",
    lastUpdated: "2026-09-23 12:45:00",
  },
];

export const INITIAL_SOP_GUIDE: SOPGuideData = {
  workbookMap: [
    {
      tab: "Daily Work Log",
      purpose: "Operational Ledger & primary data entry for all developer tasks, PRs, blockers, hours",
      audience: "All Developers (Live daily logging)",
      frequency: "Daily (Live / End of Day)",
    },
    {
      tab: "Dashboard",
      purpose: "Executive telemetry & operational metrics auto-computed from Daily Work Log",
      audience: "Tech Lead, Founders & Team",
      frequency: "Real-time dynamic",
    },
    {
      tab: "Config",
      purpose: "Master lookup tables for developer roster, roles, repository mappings",
      audience: "Tech Lead / Admin",
      frequency: "On Team / Repo Changes",
    },
    {
      tab: "User Guide",
      purpose: "SOP reference manual, blocker escalation protocols, and engineering golden rules",
      audience: "All Engineering Personnel",
      frequency: "Static / Reference",
    },
  ],
  dailySteps: [
    "Step 1: Locate your entry row or click '+ Log Work' in the Daily Work Log",
    "Step 2: Build & Push PR in your local IDE and create PR on GitHub (e.g. #142)",
    "Step 3: Flag Blockers Fast - if blocked > 1 hour, immediately set Blocked? = 'Yes'",
    "Step 4: Log Daily Work & effort hours (typically 6.0 to 8.0 hrs/day) before signing off",
    "Step 5: Review Dashboard metrics and verify blocker triage is resolved before sprint review",
  ],
  escalationLevels: [
    {
      level: "P1 - Critical Blocker",
      trigger: "Production outage, broken master build, security vulnerability, full sprint stoppage",
      action: "Set Status = Blocked, Blocked? = Yes, Priority = Critical. Immediately post in #engineering-alerts and tag @Akshar",
      badgeColor: "bg-red-500 text-white",
    },
    {
      level: "P2 - High Blocker",
      trigger: "Awaiting external 3rd-party API key, DB access, AWS cloud IAM credentials, or staging env stall",
      action: "Log in Col M; flag in standup or tag @Manish in team chat",
      badgeColor: "bg-orange-500 text-white",
    },
    {
      level: "P3 - Medium Dependency",
      trigger: "Awaiting peer code review, UI design token clarification, or PR merge signoff",
      action: "Set Status = In Progress, Review? = Yes, assign designated Reviewer in Col O",
      badgeColor: "bg-amber-500 text-white",
    },
    {
      level: "P4 - Low / Clarification",
      trigger: "Minor UI styling tweak, documentation phrasing, non-blocking asynchronous inquiry",
      action: "Add note in Notes column (Col R) & address in next engineering sync",
      badgeColor: "bg-blue-500 text-white",
    },
  ],
  goldenRules: [
    {
      category: "Daily Logging",
      do: "Log work daily before signing off (~2 mins)",
      dont: "Don't postpone logging to the end of the week or sprint end",
    },
    {
      category: "Dropdown Chips",
      do: "Always select dropdown chips (Status, Priority, Repo, Work Type)",
      dont: "Don't type custom untyped strings in chip-validated cells",
    },
    {
      category: "Work Hours",
      do: "Log realistic effort (typically 6.0 - 8.0 hrs/day total)",
      dont: "Don't leave hours blank or enter 0 for completed tasks",
    },
    {
      category: "Blockers",
      do: "Flag immediately if stuck > 1 hour so the lead can unblock you",
      dont: "Don't wait silently until the next morning standup",
    },
    {
      category: "Sheet Integrity",
      do: "Update your own assigned rows in Daily Work Log or use the modal form",
      dont: "Don't delete columns, unmerge formulas, or alter master Config without tech lead signoff",
    },
  ],
};

// =========================================================================
// TRACK 2: FIELD MARKETING & SALES PIPELINE DATA (AXORAA MARKETING)
// Document ID: 1_m3ld9Eb_zizpDB31fOZ5w59SKPYsNoMI9Ru7f2cfDY
// =========================================================================

export const INITIAL_MARKETING_DEALS: MarketingDeal[] = [
  {
    id: "deal-1",
    leadId: "LD-1001",
    dateAdded: "2026-09-01",
    marketingPerson: "Kamil",
    companyName: "Apex FinTech Solutions",
    industry: "Financial Services / NeoBanking",
    contactPerson: "Rajiv Malhotra",
    designation: "Chief Technology Officer",
    phoneNumber: "+91 98450 11223",
    emailAddress: "rajiv.m@apexfintech.io",
    officeAddress: "Tech Park Phase 2, Whitefield",
    city: "Bangalore",
    stateRegion: "Karnataka",
    googleMapsLink: "https://maps.google.com/?q=Whitefield+Bangalore",
    leadSource: "Referral",
    initialVisitDate: "2026-09-03",
    lastInteractionDate: "2026-09-20",
    visitType: "Commercial Negotiation",
    isDecisionMaker: true,
    decisionMakerDetails: "Rajiv Malhotra (CTO) & Board",
    clientRequirements: "High-throughput core transaction ledger with sub-50ms latency",
    solutionsPitched: "SeekFactory Core Microservice & Transaction Mesh",
    budgetSpecified: 2500000,
    estimatedDealValue: 2500000,
    weightedValue: 2500000,
    demoRequired: "Completed",
    proposalSent: true,
    proposalValue: 2500000,
    leadStatus: "Closed Won",
    nextFollowUpDate: "2026-10-01",
    followUpAction: "Q4 Renewal Scoping & Expansion",
    followUpPriority: "Medium",
    followUpStatus: "Completed",
    daysSinceLastVisit: 3,
    dueStatus: "Completed",
    conversionDate: "2026-09-15",
    notesNextSteps: "Account live in production. 100% payments collected.",
  },
  {
    id: "deal-2",
    leadId: "LD-1002",
    dateAdded: "2026-09-05",
    marketingPerson: "Anusha",
    companyName: "GreenPulse Logistics",
    industry: "Logistics & Supply Chain",
    contactPerson: "Virendra Singh",
    designation: "VP Operations",
    phoneNumber: "+91 98110 44556",
    emailAddress: "v.singh@greenpulse.com",
    officeAddress: "Cyber City Tower C",
    city: "Gurugram",
    stateRegion: "Haryana",
    googleMapsLink: "https://maps.google.com/?q=Cyber+City+Gurugram",
    leadSource: "Field Visit / Direct Walk-in",
    initialVisitDate: "2026-09-08",
    lastInteractionDate: "2026-09-21",
    visitType: "Technical Scoping",
    isDecisionMaker: false,
    decisionMakerDetails: "Suresh Gupta (Managing Director)",
    clientRequirements: "IoT GPS Telematics & automated fleet route dispatch",
    solutionsPitched: "Axoraa Fleet Telematics Engine & Driver APK",
    budgetSpecified: 2000000,
    estimatedDealValue: 1800000,
    weightedValue: 1800000,
    demoRequired: "Completed",
    proposalSent: true,
    proposalValue: 1800000,
    leadStatus: "Closed Won",
    nextFollowUpDate: "2026-09-24",
    followUpAction: "Resolve GPS API sandbox credential delay with client IT",
    followUpPriority: "High",
    followUpStatus: "In Progress",
    daysSinceLastVisit: 2,
    dueStatus: "Upcoming",
    conversionDate: "2026-09-12",
    notesNextSteps: "Milestone 2 underway (60%). Overdue invoice INV-2026-004 (₹6L) pending settlement.",
  },
  {
    id: "deal-3",
    leadId: "LD-1003",
    dateAdded: "2026-09-07",
    marketingPerson: "Kamil",
    companyName: "Zeta AI Labs",
    industry: "Artificial Intelligence & SaaS",
    contactPerson: "Dr. Arvind Swaminathan",
    designation: "Founder & CEO",
    phoneNumber: "+91 99200 77889",
    emailAddress: "arvind@zeta-ai.org",
    officeAddress: "Indiranagar 100ft Road",
    city: "Bangalore",
    stateRegion: "Karnataka",
    googleMapsLink: "https://maps.google.com/?q=Indiranagar+Bangalore",
    leadSource: "LinkedIn / Outreach",
    initialVisitDate: "2026-09-10",
    lastInteractionDate: "2026-09-22",
    visitType: "Commercial Negotiation",
    isDecisionMaker: true,
    decisionMakerDetails: "Dr. Arvind (Sole Founder)",
    clientRequirements: "Real-time streaming conversational agent orchestrator with multi-modal caching",
    solutionsPitched: "SeekFactory LLM Gateway & Redis Cluster",
    budgetSpecified: 3000000,
    estimatedDealValue: 2800000,
    weightedValue: 2240000, // 80% prob
    demoRequired: "Completed",
    proposalSent: true,
    proposalValue: 2800000,
    leadStatus: "Negotiation",
    nextFollowUpDate: "2026-09-25",
    followUpAction: "Final contract signoff meeting with legal counsel",
    followUpPriority: "High",
    followUpStatus: "In Progress",
    daysSinceLastVisit: 1,
    dueStatus: "Upcoming",
    notesNextSteps: "Commercial terms approved; founder closing agreement for ₹28L contract.",
  },
  {
    id: "deal-4",
    leadId: "LD-1004",
    dateAdded: "2026-09-10",
    marketingPerson: "Anusha",
    companyName: "Bharat Mobility",
    industry: "Automotive / EV Infrastructure",
    contactPerson: "Pooja Hegde",
    designation: "Head of Digital Products",
    phoneNumber: "+91 97311 33221",
    emailAddress: "p.hegde@bharatmobility.in",
    officeAddress: "MIDC Andheri East",
    city: "Mumbai",
    stateRegion: "Maharashtra",
    googleMapsLink: "https://maps.google.com/?q=Andheri+East+Mumbai",
    leadSource: "Exhibition / Event",
    initialVisitDate: "2026-09-14",
    lastInteractionDate: "2026-09-19",
    visitType: "Product Demo",
    isDecisionMaker: false,
    decisionMakerDetails: "Karthik Nair (Executive Director)",
    clientRequirements: "EV battery swapping station reservation & billing app",
    solutionsPitched: "SeekFactory Mobile Client & IoT Sync",
    budgetSpecified: 2200000,
    estimatedDealValue: 2000000,
    weightedValue: 1200000, // 60% prob
    demoRequired: "Completed",
    proposalSent: true,
    proposalValue: 2000000,
    leadStatus: "Proposal Sent",
    nextFollowUpDate: "2026-09-24",
    followUpAction: "Commercial review of submitted proposal",
    followUpPriority: "High",
    followUpStatus: "Pending",
    daysSinceLastVisit: 4,
    dueStatus: "Upcoming",
    notesNextSteps: "Formal proposal submitted for ₹20L. Awaiting executive signoff.",
  },
  {
    id: "deal-5",
    leadId: "LD-1005",
    dateAdded: "2026-09-12",
    marketingPerson: "Kamil",
    companyName: "SwiftLogistics Corp",
    industry: "Supply Chain & Warehousing",
    contactPerson: "Mohit Chawla",
    designation: "Director of IT",
    phoneNumber: "+91 98990 66778",
    emailAddress: "mohit@swiftlogistics.co",
    officeAddress: "Sector 62, Electronic City",
    city: "Noida",
    stateRegion: "Uttar Pradesh",
    googleMapsLink: "https://maps.google.com/?q=Sector+62+Noida",
    leadSource: "Cold Call",
    initialVisitDate: "2026-09-16",
    lastInteractionDate: "2026-09-21",
    visitType: "Intro Meeting",
    isDecisionMaker: true,
    decisionMakerDetails: "Mohit Chawla",
    clientRequirements: "Warehouse inventory barcoding & automated stock reconciliation",
    solutionsPitched: "SeekFactory Warehouse Mobile APK",
    budgetSpecified: 1000000,
    estimatedDealValue: 900000,
    weightedValue: 360000, // 40% prob
    demoRequired: "Scheduled",
    proposalSent: false,
    proposalValue: 0,
    leadStatus: "Meeting Scheduled",
    nextFollowUpDate: "2026-09-26",
    followUpAction: "Conduct on-site software demo for operations staff",
    followUpPriority: "Medium",
    followUpStatus: "Pending",
    daysSinceLastVisit: 2,
    dueStatus: "Upcoming",
    notesNextSteps: "Demo scheduled for Friday 3 PM. Bhuvan to support technical demo.",
  },
];

export const INITIAL_INTERACTIONS: MarketingInteraction[] = [
  {
    id: "int-1",
    date: "2026-09-22",
    marketingPerson: "Kamil",
    companyName: "Zeta AI Labs",
    leadId: "LD-1003",
    googleMapsLink: "https://maps.google.com/?q=Indiranagar+Bangalore",
    leadSource: "LinkedIn / Outreach",
    interactionType: "Commercial Negotiation",
    meetingMode: "Physical (On-site)",
    personsMet: "Dr. Arvind Swaminathan (Founder)",
    designation: "Founder & CEO",
    phoneNumber: "+91 99200 77889",
    email: "arvind@zeta-ai.org",
    agenda: "Finalize SLA, security audits, and payment milestones for ₹28L deal",
    discussionFeedback: "Client agreed to 40% advance upon contract signing. Delighted with microservice latency demo.",
    demoRequired: "Completed",
    interestLevel: "Hot",
    probabilityPct: 85,
    interactionOutcome: "Positive - Advancing",
    actionItemsAgreed: "Send revised master service agreement by Wednesday morning",
    nextSteps: "Schedule contract execution meeting with Adnaan & Akshar",
    nextFollowUpDate: "2026-09-25",
    followUpPriority: "High",
    loggedBy: "Kamil (2026-09-22 17:30)",
  },
  {
    id: "int-2",
    date: "2026-09-21",
    marketingPerson: "Anusha",
    companyName: "GreenPulse Logistics",
    leadId: "LD-1002",
    googleMapsLink: "https://maps.google.com/?q=Cyber+City+Gurugram",
    leadSource: "Field Visit / Direct Walk-in",
    interactionType: "Follow-up",
    meetingMode: "Physical (On-site)",
    personsMet: "Virendra Singh, Rajesh (IT Admin)",
    designation: "VP Operations",
    phoneNumber: "+91 98110 44556",
    email: "v.singh@greenpulse.com",
    agenda: "Discuss pending invoice INV-2026-004 (₹6L) and unblock GPS API sandbox",
    discussionFeedback: "Virendra confirmed finance clearance scheduled for next payment run. IT promised sandbox access.",
    demoRequired: "No",
    interestLevel: "Warm",
    probabilityPct: 90,
    interactionOutcome: "Follow-up Required",
    actionItemsAgreed: "IT admin to whitelist Axoraa IP addresses for telematics ingestion",
    nextSteps: "Follow up with finance lead for ₹6L overdue invoice clearance",
    nextFollowUpDate: "2026-09-24",
    followUpPriority: "High",
    loggedBy: "Anusha (2026-09-21 16:15)",
  },
  {
    id: "int-3",
    date: "2026-09-20",
    marketingPerson: "Kamil",
    companyName: "SwiftLogistics Corp",
    leadId: "LD-1005",
    googleMapsLink: "https://maps.google.com/?q=Sector+62+Noida",
    leadSource: "Cold Call",
    interactionType: "Intro Meeting",
    meetingMode: "Virtual (Video)",
    personsMet: "Mohit Chawla (Director)",
    designation: "Director of IT",
    phoneNumber: "+91 98990 66778",
    email: "mohit@swiftlogistics.co",
    agenda: "Product walkthrough of warehouse barcoding mobile APK",
    discussionFeedback: "Client currently using manual Excel ledgers. Strongly keen on mobile inventory audits.",
    demoRequired: "Yes",
    interestLevel: "Warm",
    probabilityPct: 45,
    interactionOutcome: "Needs Demo",
    actionItemsAgreed: "Prepare staging instance with sample warehouse SKU dataset",
    nextSteps: "Run live on-site demo on Friday with mobile client lead (Bhuvan)",
    nextFollowUpDate: "2026-09-26",
    followUpPriority: "Medium",
    loggedBy: "Kamil (2026-09-20 11:00)",
  },
];

// =========================================================================
// TRACK 3: FOUNDERS & EXECUTIVE COMMAND CENTER DATA
// Complete metrics, Founder matrix, 8 Clients, 5 Delivery projects, Billing
// =========================================================================

export const COMPANY_TOP_LINE_METRICS: CompanyTopLineMetrics = {
  totalClients: 8,
  activeProjects: 5,
  completedProjects: 1,
  projectsOnHold: 1,
  futureOpps: 5,
  totalDealValue: 15900000, // ₹1,59,00,000 (₹1.59 Cr)
  totalInvoiced: 7800000,   // ₹78,00,000 (₹78 L)
  totalReceived: 6000000,   // ₹60,00,000 (₹60 L)
  totalPending: 1800000,    // ₹18,00,000 (₹18 L)
  overduePayments: 600000,  // ₹6,00,000 (₹6 L)
};

export const INITIAL_FOUNDER_MATRIX: FounderMatrixStats[] = [
  {
    founder: "Akshar",
    role: "Tech Lead / Systems Lead",
    clientsBrought: 2,
    totalDealValue: 4000000, // ₹40,00,000
    projectsLed: {
      total: 2,
      completed: 1, // Apex FinTech (PRJ-001)
      active: 0,
      onHold: 1,    // Omnikart Retail (PRJ-005)
    },
    pendingCollection: 1000000, // ₹10,00,000
  },
  {
    founder: "Abhinav",
    role: "Frontend Lead / Web Architect",
    clientsBrought: 2,
    totalDealValue: 3800000, // ₹38,00,000 (GreenPulse ₹18L + Bharat Mobility ₹20L)
    projectsLed: {
      total: 2,
      completed: 0,
      active: 2,    // GreenPulse (PRJ-002) + Bharat Mobility
      onHold: 0,
    },
    pendingCollection: 3200000, // ₹32,00,000
  },
  {
    founder: "Adnaan",
    role: "Platform Lead / Integration",
    clientsBrought: 2,
    totalDealValue: 4000000, // ₹40,00,000 (CloudScale ₹12L + Zeta AI ₹28L)
    projectsLed: {
      total: 2,
      completed: 0,
      active: 1,    // CloudScale (PRJ-003)
      onHold: 0,
    },
    pendingCollection: 3200000, // ₹32,00,000
  },
  {
    founder: "Bhuvan",
    role: "Mobile Lead / Cross-Platform",
    clientsBrought: 2,
    totalDealValue: 4100000, // ₹41,00,000 (NexaHealth ₹32L + SwiftLogistics ₹9L)
    projectsLed: {
      total: 2,
      completed: 0,
      active: 1,    // NexaHealth (PRJ-004)
      onHold: 0,
    },
    pendingCollection: 2500000, // ₹25,00,000
  },
];

export const INITIAL_CLIENT_MASTER: ClientMasterRecord[] = [
  {
    id: "cl-1",
    clientId: "SF-001",
    projectId: "PRJ-001",
    companyName: "Apex FinTech Solutions",
    industry: "Financial Services / NeoBanking",
    salesOwner: "Akshar",
    dealValue: 2500000, // ₹25L
    dealStatus: "Won",
    contractScope: "Core NeoBank Microservices & Ledger Engine",
    signedDate: "2026-01-10",
    deliveryStatus: "Completed",
  },
  {
    id: "cl-2",
    clientId: "SF-002",
    projectId: "PRJ-002",
    companyName: "GreenPulse Logistics",
    industry: "Logistics & Fleet Telematics",
    salesOwner: "Abhinav",
    dealValue: 1800000, // ₹18L
    dealStatus: "Won",
    contractScope: "Real-time Telematics Web Platform & Driver App",
    signedDate: "2026-03-15",
    deliveryStatus: "Development",
  },
  {
    id: "cl-3",
    clientId: "SF-003",
    projectId: "PRJ-003",
    companyName: "CloudScale Systems",
    industry: "Cloud Infrastructure / DevOps",
    salesOwner: "Adnaan",
    dealValue: 1200000, // ₹12L
    dealStatus: "Won",
    contractScope: "DevOps Orchestration Engine & Automated Runners",
    signedDate: "2026-04-01",
    deliveryStatus: "Testing",
  },
  {
    id: "cl-4",
    clientId: "SF-004",
    projectId: "PRJ-004",
    companyName: "NexaHealth Diagnostics",
    industry: "Healthcare / Diagnostics Portal",
    salesOwner: "Bhuvan",
    dealValue: 3200000, // ₹32L
    dealStatus: "Won",
    contractScope: "Clinical Portal & Cross-Platform Mobile Client",
    signedDate: "2026-05-12",
    deliveryStatus: "Client Review",
  },
  {
    id: "cl-5",
    clientId: "SF-005",
    projectId: "PRJ-005",
    companyName: "Omnikart Retail",
    industry: "E-Commerce Marketplace",
    salesOwner: "Akshar",
    dealValue: 1500000, // ₹15L
    dealStatus: "Won",
    contractScope: "Multi-Vendor Marketplace & Checkout Funnel",
    signedDate: "2026-06-20",
    deliveryStatus: "On Hold",
  },
  {
    id: "cl-6",
    clientId: "SF-006",
    companyName: "Bharat Mobility",
    industry: "Automotive / EV Swapping",
    salesOwner: "Abhinav",
    dealValue: 2000000, // ₹20L
    dealStatus: "Proposal Sent",
    contractScope: "EV Battery Swapping Reservation & IoT Platform",
    signedDate: "2026-09-14",
    deliveryStatus: "Development",
  },
  {
    id: "cl-7",
    clientId: "SF-007",
    companyName: "Zeta AI Labs",
    industry: "Artificial Intelligence / Conversational",
    salesOwner: "Adnaan",
    dealValue: 2800000, // ₹28L
    dealStatus: "Negotiation",
    contractScope: "High-Throughput Conversational AI Orchestrator",
    signedDate: "2026-09-18",
    deliveryStatus: "Development",
  },
  {
    id: "cl-8",
    clientId: "SF-008",
    companyName: "SwiftLogistics Corp",
    industry: "Warehousing & Supply Chain",
    salesOwner: "Bhuvan",
    dealValue: 900000, // ₹9L
    dealStatus: "Discussion",
    contractScope: "Warehouse Inventory Barcode Scanning Mobile APK",
    signedDate: "2026-09-20",
    deliveryStatus: "Development",
  },
];

export const INITIAL_PROJECT_PROGRESS: ProjectProgressRecord[] = [
  {
    id: "pp-1",
    projectId: "PRJ-001",
    clientId: "SF-001",
    projectName: "NeoBank Core Ledger (Apex FinTech)",
    projectManager: "Akshar",
    status: "Completed",
    completionPercentage: 100,
    blockerDetails: "None - Live in Production",
    blockerOwner: "-",
    targetReleaseDate: "2026-08-15",
  },
  {
    id: "pp-2",
    projectId: "PRJ-002",
    clientId: "SF-002",
    projectName: "Fleet Telematics Engine (GreenPulse)",
    projectManager: "Abhinav",
    status: "Development",
    completionPercentage: 60.0,
    blockerDetails: "Waiting on GPS API Sandbox credentials from client IT",
    blockerOwner: "Abhinav",
    targetReleaseDate: "2026-10-30",
  },
  {
    id: "pp-3",
    projectId: "PRJ-003",
    clientId: "SF-003",
    projectName: "DevOps Orchestrator (CloudScale)",
    projectManager: "Adnaan",
    status: "Testing",
    completionPercentage: 82.2,
    blockerDetails: "Client Security Audit Clearance pending final penetration report",
    blockerOwner: "Adnaan",
    targetReleaseDate: "2026-10-15",
  },
  {
    id: "pp-4",
    projectId: "PRJ-004",
    clientId: "SF-004",
    projectName: "Clinical Diagnostics Portal (NexaHealth)",
    projectManager: "Bhuvan",
    status: "Client Review",
    completionPercentage: 88.9,
    blockerDetails: "Awaiting Razorpay/Stripe production payment gateway credentials",
    blockerOwner: "Bhuvan",
    targetReleaseDate: "2026-10-10",
  },
  {
    id: "pp-5",
    projectId: "PRJ-005",
    clientId: "SF-005",
    projectName: "Marketplace Platform (Omnikart)",
    projectManager: "Akshar",
    status: "On Hold",
    completionPercentage: 30.0,
    blockerDetails: "Scope Creep Re-negotiation - client added 14 new custom workflows",
    blockerOwner: "Akshar",
    targetReleaseDate: "2026-11-30",
  },
];

export const INITIAL_PAYMENT_BILLING: PaymentBillingRecord[] = [
  {
    id: "pay-1",
    invoiceId: "INV-2026-001",
    clientId: "SF-001",
    projectId: "PRJ-001",
    companyName: "Apex FinTech Solutions",
    invoicedAmount: 2500000,
    receivedAmount: 2500000,
    pendingAmount: 0,
    overdueAmount: 0,
    status: "Fully Paid",
    dueDate: "2026-08-01",
    milestoneDescription: "100% Contract Value (Milestones 1, 2 & Final Signoff)",
  },
  {
    id: "pay-2",
    invoiceId: "INV-2026-002",
    clientId: "SF-002",
    projectId: "PRJ-002",
    companyName: "GreenPulse Logistics",
    invoicedAmount: 600000,
    receivedAmount: 600000,
    pendingAmount: 0,
    overdueAmount: 0,
    status: "Fully Paid",
    dueDate: "2026-04-15",
    milestoneDescription: "Milestone 1: Architectural Design & Wireframes",
  },
  {
    id: "pay-3",
    invoiceId: "INV-2026-003",
    clientId: "SF-003",
    projectId: "PRJ-003",
    companyName: "CloudScale Systems",
    invoicedAmount: 800000,
    receivedAmount: 800000,
    pendingAmount: 0,
    overdueAmount: 0,
    status: "Fully Paid",
    dueDate: "2026-05-30",
    milestoneDescription: "Milestone 1: Orchestration Core Engine",
  },
  {
    id: "pay-4",
    invoiceId: "INV-2026-004",
    clientId: "SF-002",
    projectId: "PRJ-002",
    companyName: "GreenPulse Logistics",
    invoicedAmount: 600000,
    receivedAmount: 0,
    pendingAmount: 600000,
    overdueAmount: 600000, // Overdue ₹6L as highlighted in user prompt
    status: "Overdue",
    dueDate: "2026-09-01",
    milestoneDescription: "Milestone 2: Real-time GPS Streaming API",
  },
  {
    id: "pay-5",
    invoiceId: "INV-2026-005",
    clientId: "SF-003",
    projectId: "PRJ-003",
    companyName: "CloudScale Systems",
    invoicedAmount: 400000,
    receivedAmount: 0,
    pendingAmount: 400000,
    overdueAmount: 0,
    status: "Pending",
    dueDate: "2026-10-05",
    milestoneDescription: "Milestone 2: Security Hardening & Audit Clearance",
  },
  {
    id: "pay-6",
    invoiceId: "INV-2026-006",
    clientId: "SF-004",
    projectId: "PRJ-004",
    companyName: "NexaHealth Diagnostics",
    invoicedAmount: 1600000,
    receivedAmount: 1600000,
    pendingAmount: 0,
    overdueAmount: 0,
    status: "Fully Paid",
    dueDate: "2026-06-30",
    milestoneDescription: "Milestone 1 & 2: Clinical Workflow & Cross-Platform UI",
  },
  {
    id: "pay-7",
    invoiceId: "INV-2026-007",
    clientId: "SF-004",
    projectId: "PRJ-004",
    companyName: "NexaHealth Diagnostics",
    invoicedAmount: 800000,
    receivedAmount: 0,
    pendingAmount: 800000,
    overdueAmount: 0,
    status: "Pending",
    dueDate: "2026-09-20", // Due Sept 20 as specified in prompt
    milestoneDescription: "Milestone 3: Payment Gateway & Production Deployment",
  },
  {
    id: "pay-8",
    invoiceId: "INV-2026-008",
    clientId: "SF-005",
    projectId: "PRJ-005",
    companyName: "Omnikart Retail",
    invoicedAmount: 500000,
    receivedAmount: 500000,
    pendingAmount: 0,
    overdueAmount: 0,
    status: "Fully Paid",
    dueDate: "2026-07-15",
    milestoneDescription: "Contract Advance Payment (Project currently paused)",
  },
];
